# Generated by Django 5.2.8 on 2025-11-23 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_clientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='bar_council_id',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='advocateprofile',
            name='bar_council_enrollment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_council_id',
            field=models.FileField(blank=True, null=True, upload_to='bar_council_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='advocate_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('advocate', 'Advocate')], default='client', max_length=10),
        ),
    ]
