# Generated by Django 5.2.8 on 2025-11-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_advocateprofile_bar_council_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='bar_council_enrollment',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='advocateprofile',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='state',
        ),
    ]
