# Generated by Django 5.2.8 on 2025-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/og/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
